/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BouquetRouteImport } from './routes/bouquet'
import { Route as CautionRouteImport } from './routes/caution'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as LoveRouteImport } from './routes/love'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as SurpriseRouteImport } from './routes/surprise'
import { Route as UsRouteImport } from './routes/us'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BouquetRoute = BouquetRouteImport.update({
  id: '/bouquet',
  path: '/bouquet',
  getParentRoute: () => rootRouteImport,
} as any)
const CautionRoute = CautionRouteImport.update({
  id: '/caution',
  path: '/caution',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoveRoute = LoveRouteImport.update({
  id: '/love',
  path: '/love',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const SurpriseRoute = SurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => rootRouteImport,
} as any)
const UsRoute = UsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bouquet': typeof BouquetRoute
  '/caution': typeof CautionRoute
  '/letter': typeof LetterRoute
  '/love': typeof LoveRoute
  '/memories': typeof MemoriesRoute
  '/surprise': typeof SurpriseRoute
  '/us': typeof UsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bouquet': typeof BouquetRoute
  '/caution': typeof CautionRoute
  '/letter': typeof LetterRoute
  '/love': typeof LoveRoute
  '/memories': typeof MemoriesRoute
  '/surprise': typeof SurpriseRoute
  '/us': typeof UsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bouquet': typeof BouquetRoute
  '/caution': typeof CautionRoute
  '/letter': typeof LetterRoute
  '/love': typeof LoveRoute
  '/memories': typeof MemoriesRoute
  '/surprise': typeof SurpriseRoute
  '/us': typeof UsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bouquet'
    | '/caution'
    | '/letter'
    | '/love'
    | '/memories'
    | '/surprise'
    | '/us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bouquet'
    | '/caution'
    | '/letter'
    | '/love'
    | '/memories'
    | '/surprise'
    | '/us'
  id:
    | '__root__'
    | '/'
    | '/bouquet'
    | '/caution'
    | '/letter'
    | '/love'
    | '/memories'
    | '/surprise'
    | '/us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BouquetRoute: typeof BouquetRoute
  CautionRoute: typeof CautionRoute
  LetterRoute: typeof LetterRoute
  LoveRoute: typeof LoveRoute
  MemoriesRoute: typeof MemoriesRoute
  SurpriseRoute: typeof SurpriseRoute
  UsRoute: typeof UsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bouquet': {
      id: '/bouquet'
      path: '/bouquet'
      fullPath: '/bouquet'
      preLoaderRoute: typeof BouquetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caution': {
      id: '/caution'
      path: '/caution'
      fullPath: '/caution'
      preLoaderRoute: typeof CautionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/love': {
      id: '/love'
      path: '/love'
      fullPath: '/love'
      preLoaderRoute: typeof LoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surprise': {
      id: '/surprise'
      path: '/surprise'
      fullPath: '/surprise'
      preLoaderRoute: typeof SurpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us': {
      id: '/us'
      path: '/us'
      fullPath: '/us'
      preLoaderRoute: typeof UsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BouquetRoute: BouquetRoute,
  CautionRoute: CautionRoute,
  LetterRoute: LetterRoute,
  LoveRoute: LoveRoute,
  MemoriesRoute: MemoriesRoute,
  SurpriseRoute: SurpriseRoute,
  UsRoute: UsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
